menu:
  home: Home
  archives: Archives
  tags: Tags
  categories: Categories
  links: Links
  about: About

posts:
  prev: Prev
  next: Next
  prev_post: Prev
  next_post: Next
  readmore: Read more..

copyright:
  author: 'Author'
  link: 'Link'
  license: 'License'

footer:
  powered: "Powered by %s"