# Header
menu:
  Home: /
  Archives: /archives
  Links: /links
  About: /about/me
  
node_sass:
  debug: false
  outputStyle: expanded
  precision: 5
  sourceComments: false
  indentWidth: 2

copyright:
  # https://creativecommons.org/
  license: '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>'
